Scheduler changes to support vertical resources scaling
Huawei-PaaS/kubernetes pull request #25
Opened 2018-09-24 17:35 UTC by vinaykul

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2018-09-27 22:26 UTC, pdgetrf requested changes
comments inline

2018-09-27 22:26 UTC, pdgetrf commented on pkg/scheduler/cache/cache.go
> +			containerResourcesRequests = resizeContainer.Resources.Requests
cannot overwrite the whole request because the annotation from controller only contains request that changed. for example if there are both cpu and memory in pod request, and only memory is changed. annotation from controller will be a container with only memory request. this is different from the POC implementation.

2018-09-27 22:26 UTC, pdgetrf commented on pkg/scheduler/cache/cache.go
> +func (cache *schedulerCache) getPodResizeRequirements(pod *v1.Pod, resizeRequestAnnotation string) (map[string]v1.Container, *Resource, error) {
this needs unit tests

2018-09-27 22:26 UTC, pdgetrf commented on pkg/scheduler/cache/cache.go
> +						newPod.Spec.Containers[i].Resources = resizeContainer.Resources
same issue here. resizeContainer only contains the resource changed.

2018-09-29 02:27 UTC, vinaykul commented on pkg/scheduler/cache/cache.go
> +			containerResourcesRequests = resizeContainer.Resources.Requests
fixed, will send review shortly.

2018-09-29 02:29 UTC, vinaykul commented on pkg/scheduler/cache/cache.go
> +func (cache *schedulerCache) getPodResizeRequirements(pod *v1.Pod, resizeRequestAnnotation string) (map[string]v1.Container, *Resource, error) {
currently covered by the new unit test TestUpdatePodResources. I'll add some tests for the internal functions next week.

2018-09-29 02:29 UTC, vinaykul commented on pkg/scheduler/cache/cache.go
> +						newPod.Spec.Containers[i].Resources = resizeContainer.Resources
fixed. will send review shortly.

2018-09-30 18:44 UTC, vinaykul commented
I've fixed the code review items except for additional tests for the newly added helper functions (they are covered by the new test indirectly). The forward-merge from vertical-scaling to my scheduler staging branch is a mess due to the accidental kubelet commit/revert earlier. I'm going to close this PR and send a new PR for scheduler changes.

2018-09-30 18:44 UTC, closed without merging